version: '3.8'
services:

  db:
    image: postgres:alpine
    container_name: db
    ports:
      - ${HOST_PORT}:${PSQL_PORT}
    environment:
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${MAIN_DB},${QUEUE_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
